### ISSUE TITLE
Proportional fonts? 

### ISSUE THREAD

**Issue by boussou** [aarzilli/nucular#29]
I see that demos exclusively make use of monospaced font.
Currently it uses DroidSansMono.ttf, would it work (said differently "is it tested?") with a font not mono.
like ie DroidSans.ttf not monospaced?

**Comment by aarzilli** [comment]
>is it tested?

Not particularly because I don't use it, but it probably works:

![nucular with proportional font](https://i.imgur.com/RJbNClt.png)

IMHO there's something wrong with the kerning of Droid Sans, but that's the [text rendering library](github.com/golang/freetype/truetype), not nucular, and usually it works fine.

**Comment by boussou** [comment]
Agreed.
Based on your screenshot, it is just a matter of choosing the proper font, and even with this potential kerning problem it is still usable & readable.
Awesome.

**Comment by aarzilli** [comment]
I was using a fractional font size, using an integer one looks better:

![nucular proportional better](https://i.imgur.com/iPkRcKX.png)

**Comment by boussou** [comment]
Can you tell us how you change the font?

I tried /usr/bin/go-bindata -o internal/assets/assets.go -pkg assets AmazonEmber_Rg.ttf
then go build in the $GOPATH/src ...nucular.

When Ibuild the "overview" demo,  it doesn't change anything.
as well, I tried to change background of White theme (to real white). 
Nothing taken into account.

Thanks

**Comment by aarzilli** [comment]
See https://github.com/aarzilli/nucular/issues/22#issuecomment-445186650
